spec/spec_helper.rb:
  mock_with: ':rspec'
Rakefile:
  extras:
    - |
      Blacksmith::RakeTask.new do |t|
        t.tag_pattern = "%s"
        t.tag_message_pattern = "Release ssm-nifi_registry %s"
        t.tag_sign = true
      end
